### ISSUE TITLE
Add AMIRIS outputs for MPI calculations

### ISSUE THREAD

**Issue by dlr-jk** [TradeRES/toolbox-amiris-emlab#17]
This comprises

- [x] hourly RES generation
- [x] hourly supply per technology

**Comment by IngridJSJ** [comment]
conventional generation seem to be hourly the same
And error when there is storage
15:10:04 � ERROR � Fatal error during execution of action "aggregate_results":
Data manager log:
During execution of action "aggregate_results" (project: "general") the following data sets were accessed:
Traceback (most recent call last):
File "C:\Programs\Anaconda3\envs\emlabEnv\lib\site-packages\pandas\core\indexes\base.py", line 3629, in get_loc
return self._engine.get_loc(casted_key)
File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'AwardedDischargePowerInMWH'

**Comment by dlr-jk** [comment]
@IngridJSJ Could you please send me the exact input to replicate? I think, I can fix this.
